
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jan  9 2025 17:11:29 IST (Jan  9 2025 11:41:29 UTC)

// Verification Directory fv/top_dut 

module spi_master(mclk, reset, start, master_rd_wr, master_address,
     master_in_data, master_out_data, miso, mosi, cs, sclk);
  input mclk, reset, start, master_rd_wr, miso;
  input [6:0] master_address;
  input [7:0] master_out_data;
  output [7:0] master_in_data;
  output mosi, cs, sclk;
  wire mclk, reset, start, master_rd_wr, miso;
  wire [6:0] master_address;
  wire [7:0] master_out_data;
  wire [7:0] master_in_data;
  wire mosi, cs, sclk;
  wire [7:0] in_data;
  wire [31:0] count;
  wire [7:0] header;
  wire [7:0] out_data;
  wire inc_add_88_20_n_251, inc_add_88_20_n_256, inc_add_88_20_n_261,
       inc_add_88_20_n_264, inc_add_88_20_n_267, inc_add_88_20_n_273,
       inc_add_88_20_n_276, inc_add_88_20_n_279;
  wire inc_add_88_20_n_285, inc_add_88_20_n_290, inc_add_88_20_n_295,
       inc_add_88_20_n_298, inc_add_88_20_n_301, inc_add_88_20_n_307,
       inc_add_88_20_n_312, inc_add_88_20_n_315;
  wire inc_add_88_20_n_318, inc_add_88_20_n_324, inc_add_88_20_n_329,
       inc_add_88_20_n_332, inc_add_88_20_n_335, inc_add_88_20_n_338,
       inc_add_88_20_n_341, inc_add_88_20_n_347;
  wire inc_add_88_20_n_352, inc_add_88_20_n_355, inc_add_88_20_n_358,
       inc_add_88_20_n_362, inc_add_88_20_n_366, inc_add_88_20_n_371,
       inc_add_88_20_n_376, inc_add_88_20_n_379;
  wire inc_add_88_20_n_382, inc_add_88_20_n_388, inc_add_88_20_n_393,
       inc_add_88_20_n_396, inc_add_88_20_n_399, inc_add_88_20_n_405,
       inc_add_88_20_n_410, inc_add_88_20_n_415;
  wire inc_add_88_20_n_418, inc_add_88_20_n_419, inc_add_88_20_n_422,
       inc_add_88_20_n_425, inc_add_88_20_n_426, inc_add_88_20_n_445,
       n_0, n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_89;
  wire n_90, n_91, n_92, n_93, n_94, n_95, n_96, n_97;
  wire n_98, n_99, n_100, n_101, n_102, n_103, n_104, n_105;
  wire n_106, n_107, n_108, n_109, n_110, n_111, n_112, n_113;
  wire n_114, n_115, n_116, n_117, n_118, n_119, n_120, n_121;
  wire n_122, n_123, n_124, n_125, n_126, n_127, n_128, n_129;
  wire n_130, n_131, n_132, n_133, n_134, n_135, n_136, n_180;
  wire n_181, n_182, n_183, n_184, n_185, n_186, n_187, n_188;
  wire n_189, n_190, n_191, n_192, n_193, n_194, n_195, n_196;
  wire n_197, n_198, n_199, n_200, n_201, n_202, n_203, n_204;
  wire n_205, n_206, n_207, n_208, n_209, n_210, n_211;
  assign count[31] = 1'b0;
  assign count[30] = 1'b0;
  assign count[29] = 1'b0;
  assign count[28] = 1'b0;
  assign count[27] = 1'b0;
  assign count[26] = 1'b0;
  assign count[25] = 1'b0;
  assign count[24] = 1'b0;
  assign count[23] = 1'b0;
  assign count[22] = 1'b0;
  assign count[21] = 1'b0;
  assign count[20] = 1'b0;
  assign count[19] = 1'b0;
  assign count[18] = 1'b0;
  assign count[17] = 1'b0;
  assign count[16] = 1'b0;
  assign count[15] = 1'b0;
  assign count[14] = 1'b0;
  assign count[13] = 1'b0;
  assign count[12] = 1'b0;
  assign count[11] = 1'b0;
  assign count[10] = 1'b0;
  assign count[9] = 1'b0;
  assign count[8] = 1'b0;
  assign count[7] = 1'b0;
  assign count[6] = 1'b0;
  assign count[5] = 1'b0;
  assign count[4] = 1'b0;
  assign count[3] = 1'b0;
  assign count[2] = 1'b0;
  assign count[1] = 1'b0;
  assign count[0] = 1'b0;
  DFFQXL \master_in_data_reg[4] (.CK (cs), .D (in_data[4]), .Q
       (master_in_data[4]));
  DFFQXL \master_in_data_reg[6] (.CK (cs), .D (in_data[6]), .Q
       (master_in_data[6]));
  DFFQXL \master_in_data_reg[7] (.CK (cs), .D (in_data[7]), .Q
       (master_in_data[7]));
  DFFQXL \master_in_data_reg[0] (.CK (cs), .D (in_data[0]), .Q
       (master_in_data[0]));
  DFFQXL \master_in_data_reg[2] (.CK (cs), .D (in_data[2]), .Q
       (master_in_data[2]));
  DFFQXL \master_in_data_reg[5] (.CK (cs), .D (in_data[5]), .Q
       (master_in_data[5]));
  DFFQXL \master_in_data_reg[3] (.CK (cs), .D (in_data[3]), .Q
       (master_in_data[3]));
  DFFQXL \master_in_data_reg[1] (.CK (cs), .D (in_data[1]), .Q
       (master_in_data[1]));
  DFFQX1 \count_reg[0]57 (.CK (mclk), .D (n_78), .Q (count[0]));
  DFFQX1 \count_reg[1]58 (.CK (mclk), .D (n_73), .Q (count[1]));
  DFFQX1 \count_reg[2]59 (.CK (mclk), .D (n_71), .Q (count[2]));
  DFFQX1 \count_reg[3]60 (.CK (mclk), .D (n_69), .Q (count[3]));
  DFFQX1 \count_reg[4]61 (.CK (mclk), .D (n_68), .Q (count[4]));
  DFFQX1 \count_reg[5]62 (.CK (mclk), .D (n_67), .Q (count[5]));
  DFFQX1 \count_reg[6]63 (.CK (mclk), .D (n_66), .Q (count[6]));
  DFFQX1 \count_reg[7]64 (.CK (mclk), .D (n_65), .Q (count[7]));
  DFFQX1 \count_reg[8]65 (.CK (mclk), .D (n_79), .Q (count[8]));
  DFFQX1 \count_reg[9]66 (.CK (mclk), .D (n_64), .Q (count[9]));
  DFFQX1 \count_reg[10]67 (.CK (mclk), .D (n_63), .Q (count[10]));
  DFFQX1 \count_reg[11]68 (.CK (mclk), .D (n_62), .Q (count[11]));
  DFFQX1 \count_reg[12]69 (.CK (mclk), .D (n_61), .Q (count[12]));
  DFFQX1 \count_reg[13]70 (.CK (mclk), .D (n_58), .Q (count[13]));
  DFFQX1 \count_reg[14]71 (.CK (mclk), .D (n_60), .Q (count[14]));
  DFFQX1 \count_reg[15]72 (.CK (mclk), .D (n_59), .Q (count[15]));
  DFFQX1 \count_reg[16]73 (.CK (mclk), .D (n_57), .Q (count[16]));
  DFFQX1 \count_reg[17]74 (.CK (mclk), .D (n_56), .Q (count[17]));
  DFFQX1 \count_reg[18]75 (.CK (mclk), .D (n_55), .Q (count[18]));
  DFFQX1 \count_reg[19]76 (.CK (mclk), .D (n_54), .Q (count[19]));
  DFFQX1 \count_reg[20]77 (.CK (mclk), .D (n_52), .Q (count[20]));
  DFFQX1 \count_reg[21]78 (.CK (mclk), .D (n_53), .Q (count[21]));
  DFFQX1 \count_reg[22]79 (.CK (mclk), .D (n_51), .Q (count[22]));
  DFFQX1 \count_reg[23]80 (.CK (mclk), .D (n_50), .Q (count[23]));
  DFFQX1 \count_reg[24]81 (.CK (mclk), .D (n_49), .Q (count[24]));
  DFFQX1 \count_reg[25]82 (.CK (mclk), .D (n_48), .Q (count[25]));
  DFFQX1 \count_reg[26]83 (.CK (mclk), .D (n_77), .Q (count[26]));
  DFFQX1 \count_reg[27]84 (.CK (mclk), .D (n_76), .Q (count[27]));
  DFFQX1 \count_reg[28]85 (.CK (mclk), .D (n_75), .Q (count[28]));
  DFFQX1 \count_reg[29]86 (.CK (mclk), .D (n_74), .Q (count[29]));
  DFFQX1 \count_reg[30]87 (.CK (mclk), .D (n_72), .Q (count[30]));
  DFFQX1 \count_reg[31]88 (.CK (mclk), .D (n_70), .Q (count[31]));
  DFFQX1 cs_reg(.CK (mclk), .D (n_96), .Q (cs));
  DFFQX1 \header_reg[0] (.CK (mclk), .D (n_103), .Q (header[0]));
  DFFQX1 \header_reg[1] (.CK (mclk), .D (n_120), .Q (header[1]));
  DFFQX1 \header_reg[2] (.CK (mclk), .D (n_119), .Q (header[2]));
  DFFQX1 \header_reg[3] (.CK (mclk), .D (n_118), .Q (header[3]));
  DFFQX1 \header_reg[4] (.CK (mclk), .D (n_112), .Q (header[4]));
  DFFQX1 \header_reg[5] (.CK (mclk), .D (n_113), .Q (header[5]));
  DFFQX1 \header_reg[6] (.CK (mclk), .D (n_114), .Q (header[6]));
  DFFQX1 \header_reg[7] (.CK (mclk), .D (n_111), .Q (header[7]));
  SDFFQX1 \in_data_reg[0] (.CK (mclk), .D (miso), .SI (in_data[0]), .SE
       (n_105), .Q (in_data[0]));
  SDFFQX1 \in_data_reg[1] (.CK (mclk), .D (in_data[0]), .SI
       (in_data[1]), .SE (n_105), .Q (in_data[1]));
  SDFFQX1 \in_data_reg[2] (.CK (mclk), .D (in_data[1]), .SI
       (in_data[2]), .SE (n_105), .Q (in_data[2]));
  SDFFQX1 \in_data_reg[3] (.CK (mclk), .D (in_data[2]), .SI
       (in_data[3]), .SE (n_105), .Q (in_data[3]));
  SDFFQX1 \in_data_reg[4] (.CK (mclk), .D (in_data[3]), .SI
       (in_data[4]), .SE (n_105), .Q (in_data[4]));
  SDFFQX1 \in_data_reg[5] (.CK (mclk), .D (in_data[4]), .SI
       (in_data[5]), .SE (n_105), .Q (in_data[5]));
  SDFFQX1 \in_data_reg[6] (.CK (mclk), .D (in_data[5]), .SI
       (in_data[6]), .SE (n_105), .Q (in_data[6]));
  SDFFQX1 \in_data_reg[7] (.CK (mclk), .D (in_data[6]), .SI
       (in_data[7]), .SE (n_105), .Q (in_data[7]));
  DFFQX1 mosi_reg(.CK (mclk), .D (n_136), .Q (mosi));
  DFFQX1 \out_data_reg[0] (.CK (mclk), .D (n_106), .Q (out_data[0]));
  DFFQX1 \out_data_reg[1] (.CK (mclk), .D (n_131), .Q (out_data[1]));
  DFFQX1 \out_data_reg[2] (.CK (mclk), .D (n_134), .Q (out_data[2]));
  DFFQX1 \out_data_reg[3] (.CK (mclk), .D (n_133), .Q (out_data[3]));
  DFFQX1 \out_data_reg[4] (.CK (mclk), .D (n_132), .Q (out_data[4]));
  DFFQX1 \out_data_reg[5] (.CK (mclk), .D (n_130), .Q (out_data[5]));
  DFFQX1 \out_data_reg[6] (.CK (mclk), .D (n_135), .Q (out_data[6]));
  DFFQX1 \out_data_reg[7] (.CK (mclk), .D (n_129), .Q (out_data[7]));
  NAND2XL g3248__2398(.A (n_121), .B (n_102), .Y (n_136));
  INVXL g3264(.A (n_128), .Y (n_135));
  INVXL g3265(.A (n_127), .Y (n_134));
  INVXL g3266(.A (n_126), .Y (n_133));
  INVXL g3267(.A (n_125), .Y (n_132));
  INVXL g3268(.A (n_124), .Y (n_131));
  INVXL g3269(.A (n_123), .Y (n_130));
  INVXL g3270(.A (n_122), .Y (n_129));
  AOI222XL g3271__5107(.A0 (n_104), .A1 (out_data[5]), .B0
       (out_data[6]), .B1 (n_0), .C0 (n_2), .C1 (master_out_data[6]),
       .Y (n_128));
  AOI222XL g3272__6260(.A0 (n_104), .A1 (out_data[1]), .B0
       (out_data[2]), .B1 (n_0), .C0 (n_2), .C1 (master_out_data[2]),
       .Y (n_127));
  AOI222XL g3273__4319(.A0 (n_104), .A1 (out_data[2]), .B0
       (out_data[3]), .B1 (n_0), .C0 (n_2), .C1 (master_out_data[3]),
       .Y (n_126));
  AOI222XL g3274__8428(.A0 (n_104), .A1 (out_data[3]), .B0
       (out_data[4]), .B1 (n_0), .C0 (n_2), .C1 (master_out_data[4]),
       .Y (n_125));
  AOI222XL g3275__5526(.A0 (n_104), .A1 (out_data[0]), .B0
       (out_data[1]), .B1 (n_0), .C0 (n_2), .C1 (master_out_data[1]),
       .Y (n_124));
  AOI222XL g3276__6783(.A0 (n_104), .A1 (out_data[4]), .B0
       (out_data[5]), .B1 (n_0), .C0 (n_2), .C1 (master_out_data[5]),
       .Y (n_123));
  AOI222XL g3277__3680(.A0 (n_104), .A1 (out_data[6]), .B0
       (out_data[7]), .B1 (n_0), .C0 (n_2), .C1 (master_out_data[7]),
       .Y (n_122));
  AOI22XL g3278__1617(.A0 (out_data[7]), .A1 (n_104), .B0 (header[7]),
       .B1 (n_99), .Y (n_121));
  INVXL g3279(.A (n_117), .Y (n_120));
  INVXL g3280(.A (n_116), .Y (n_119));
  INVXL g3281(.A (n_115), .Y (n_118));
  AOI222XL g3282__2802(.A0 (master_address[1]), .A1 (n_98), .B0 (n_99),
       .B1 (header[0]), .C0 (n_100), .C1 (header[1]), .Y (n_117));
  AOI222XL g3283__1705(.A0 (n_99), .A1 (header[1]), .B0
       (master_address[2]), .B1 (n_98), .C0 (n_100), .C1 (header[2]),
       .Y (n_116));
  AOI222XL g3284__5122(.A0 (n_99), .A1 (header[2]), .B0
       (master_address[3]), .B1 (n_98), .C0 (n_100), .C1 (header[3]),
       .Y (n_115));
  INVXL g3286(.A (n_110), .Y (n_114));
  INVXL g3287(.A (n_109), .Y (n_113));
  INVXL g3288(.A (n_108), .Y (n_112));
  INVXL g3289(.A (n_107), .Y (n_111));
  AOI222XL g3290__8246(.A0 (n_99), .A1 (header[5]), .B0
       (master_address[6]), .B1 (n_98), .C0 (n_100), .C1 (header[6]),
       .Y (n_110));
  AOI222XL g3291__7098(.A0 (n_99), .A1 (header[4]), .B0
       (master_address[5]), .B1 (n_98), .C0 (n_100), .C1 (header[5]),
       .Y (n_109));
  AOI222XL g3292__6131(.A0 (n_99), .A1 (header[3]), .B0
       (master_address[4]), .B1 (n_98), .C0 (n_100), .C1 (header[4]),
       .Y (n_108));
  AOI222XL g3293__1881(.A0 (master_rd_wr), .A1 (n_98), .B0 (n_99), .B1
       (header[6]), .C0 (n_100), .C1 (header[7]), .Y (n_107));
  AO22X1 g3294__5115(.A0 (out_data[0]), .A1 (n_0), .B0
       (master_out_data[0]), .B1 (n_2), .Y (n_106));
  NAND2XL g3295__7482(.A (n_101), .B (master_rd_wr), .Y (n_105));
  AO22X1 g3296__4733(.A0 (master_address[0]), .A1 (n_98), .B0
       (header[0]), .B1 (n_100), .Y (n_103));
  AOI21XL g3297__6161(.A0 (n_95), .A1 (n_97), .B0 (master_rd_wr), .Y
       (n_104));
  NAND3XL g3300__9315(.A (n_92), .B (reset), .C (mosi), .Y (n_102));
  OAI31XL g3301__9945(.A0 (n_4), .A1 (n_47), .A2 (n_90), .B0 (n_97), .Y
       (n_101));
  NAND2XL g3303__2883(.A (n_81), .B (n_94), .Y (n_100));
  NOR2BXL g3304__2346(.AN (n_94), .B (n_84), .Y (n_99));
  AND2X1 g3305__1666(.A (n_80), .B (n_94), .Y (n_98));
  NAND2XL g3306__7410(.A (reset), .B (n_91), .Y (n_96));
  NAND3BXL g3307__6417(.AN (n_90), .B (n_80), .C (count[4]), .Y (n_95));
  NAND2BXL g3308__5477(.AN (n_81), .B (n_94), .Y (n_97));
  AOI211XL g3310__2398(.A0 (count[4]), .A1 (count[3]), .B0 (n_85), .C0
       (n_90), .Y (n_93));
  NOR2XL g3311__5107(.A (count[4]), .B (n_90), .Y (n_94));
  OAI211XL g3312__6260(.A0 (n_36), .A1 (n_85), .B0 (n_89), .C0 (n_1),
       .Y (n_92));
  AOI22XL g3313__4319(.A0 (n_1), .A1 (n_88), .B0 (cs), .B1 (n_82), .Y
       (n_91));
  NAND4XL g3314__8428(.A (n_87), .B (n_86), .C (reset), .D (n_1), .Y
       (n_90));
  INVX1 g3315(.A (n_88), .Y (n_89));
  OAI211XL g3316__5526(.A0 (n_4), .A1 (n_80), .B0 (n_87), .C0 (n_86),
       .Y (n_88));
  NOR4BXL g3317__6783(.AN (n_42), .B (n_83), .C (count[16]), .D
       (count[23]), .Y (n_87));
  CLKINVX1 g3336(.A (n_84), .Y (n_85));
  NAND3XL g3337__3680(.A (n_40), .B (n_6), .C (n_41), .Y (n_83));
  NAND3BXL g3338__1617(.AN (n_47), .B (count[0]), .C (n_1), .Y (n_82));
  NOR4BXL g3353__2802(.AN (n_43), .B (count[17]), .C (count[9]), .D
       (n_44), .Y (n_86));
  NAND2BXL g3354__1705(.AN (n_80), .B (n_81), .Y (n_84));
  NOR2XL g3355__5122(.A (n_3), .B (n_25), .Y (n_79));
  NOR2XL g3356__8246(.A (n_3), .B (n_35), .Y (n_78));
  NOR2XL g3357__7098(.A (n_3), .B (n_38), .Y (n_77));
  NOR2XL g3358__6131(.A (n_3), .B (n_37), .Y (n_76));
  NOR2XL g3359__1881(.A (n_3), .B (n_45), .Y (n_75));
  NOR2XL g3360__5115(.A (n_3), .B (n_34), .Y (n_74));
  NOR2XL g3361__7482(.A (n_3), .B (n_39), .Y (n_73));
  NOR2XL g3362__4733(.A (n_3), .B (n_32), .Y (n_72));
  NOR2XL g3363__6161(.A (n_3), .B (n_33), .Y (n_71));
  NOR2XL g3364__9315(.A (n_3), .B (n_31), .Y (n_70));
  NOR2XL g3365__9945(.A (n_3), .B (n_30), .Y (n_69));
  NOR2XL g3366__2883(.A (n_3), .B (n_29), .Y (n_68));
  NOR2XL g3367__2346(.A (n_3), .B (n_28), .Y (n_67));
  NOR2XL g3368__1666(.A (n_3), .B (n_27), .Y (n_66));
  NOR2XL g3369__7410(.A (n_3), .B (n_26), .Y (n_65));
  NAND2XL g3370__6417(.A (n_46), .B (count[3]), .Y (n_81));
  NOR2XL g3371__5477(.A (n_46), .B (count[3]), .Y (n_80));
  NOR2XL g3372__2398(.A (n_3), .B (n_24), .Y (n_64));
  NOR2XL g3373__5107(.A (n_3), .B (n_23), .Y (n_63));
  NOR2XL g3374__6260(.A (n_3), .B (n_22), .Y (n_62));
  NOR2XL g3375__4319(.A (n_3), .B (n_21), .Y (n_61));
  NOR2XL g3376__8428(.A (n_3), .B (n_19), .Y (n_60));
  NOR2XL g3377__5526(.A (n_3), .B (n_17), .Y (n_59));
  NOR2XL g3378__6783(.A (n_3), .B (n_20), .Y (n_58));
  NOR2XL g3379__3680(.A (n_3), .B (n_16), .Y (n_57));
  NOR2XL g3380__1617(.A (n_3), .B (n_14), .Y (n_56));
  NOR2XL g3381__2802(.A (n_3), .B (n_13), .Y (n_55));
  NOR2XL g3382__1705(.A (n_3), .B (n_12), .Y (n_54));
  NOR2XL g3383__5122(.A (n_3), .B (n_18), .Y (n_53));
  NOR2XL g3384__8246(.A (n_3), .B (n_11), .Y (n_52));
  NOR2XL g3385__7098(.A (n_3), .B (n_10), .Y (n_51));
  NOR2XL g3386__6131(.A (n_3), .B (n_15), .Y (n_50));
  NOR2XL g3387__1881(.A (n_3), .B (n_9), .Y (n_49));
  NOR2XL g3388__5115(.A (n_3), .B (n_8), .Y (n_48));
  MXI2XL g3389__7482(.A (count[28]), .B (n_183), .S0 (start), .Y
       (n_45));
  OR4X1 g3390__4733(.A (count[30]), .B (count[29]), .C (count[8]), .D
       (count[24]), .Y (n_44));
  NOR4XL g3391__6161(.A (count[14]), .B (count[19]), .C (count[7]), .D
       (count[25]), .Y (n_43));
  NOR4XL g3392__9315(.A (count[27]), .B (count[22]), .C (count[28]), .D
       (count[6]), .Y (n_42));
  NOR4XL g3393__9945(.A (count[15]), .B (count[21]), .C (count[5]), .D
       (count[26]), .Y (n_41));
  NOR4XL g3394__2883(.A (count[11]), .B (count[18]), .C (count[10]), .D
       (count[12]), .Y (n_40));
  MXI2XL g3395__2346(.A (count[1]), .B (n_210), .S0 (start), .Y (n_39));
  MXI2XL g3396__1666(.A (count[26]), .B (n_185), .S0 (start), .Y
       (n_38));
  MXI2XL g3397__7410(.A (count[27]), .B (n_184), .S0 (start), .Y
       (n_37));
  AOI21XL g3398__6417(.A0 (n_5), .A1 (n_4), .B0 (master_rd_wr), .Y
       (n_36));
  MXI2XL g3399__5477(.A (count[0]), .B (n_211), .S0 (start), .Y (n_35));
  MXI2XL g3400__2398(.A (count[29]), .B (n_182), .S0 (start), .Y
       (n_34));
  MXI2XL g3401__5107(.A (count[2]), .B (n_209), .S0 (start), .Y (n_33));
  MXI2XL g3402__6260(.A (count[30]), .B (n_181), .S0 (start), .Y
       (n_32));
  MXI2XL g3403__4319(.A (count[31]), .B (n_180), .S0 (start), .Y
       (n_31));
  MXI2XL g3404__8428(.A (count[3]), .B (n_208), .S0 (start), .Y (n_30));
  MXI2XL g3405__5526(.A (count[4]), .B (n_207), .S0 (start), .Y (n_29));
  MXI2XL g3406__6783(.A (count[5]), .B (n_206), .S0 (start), .Y (n_28));
  NAND2XL g3407__3680(.A (n_7), .B (n_5), .Y (n_47));
  NAND2BXL g3408__1617(.AN (count[0]), .B (n_7), .Y (n_46));
  MXI2XL g3409__2802(.A (count[6]), .B (n_205), .S0 (start), .Y (n_27));
  MXI2XL g3410__1705(.A (count[7]), .B (n_204), .S0 (start), .Y (n_26));
  MXI2XL g3411__5122(.A (count[8]), .B (n_203), .S0 (start), .Y (n_25));
  MXI2XL g3412__8246(.A (count[9]), .B (n_202), .S0 (start), .Y (n_24));
  MXI2XL g3413__7098(.A (count[10]), .B (n_201), .S0 (start), .Y
       (n_23));
  MXI2XL g3414__6131(.A (count[11]), .B (n_200), .S0 (start), .Y
       (n_22));
  MXI2XL g3415__1881(.A (count[12]), .B (n_199), .S0 (start), .Y
       (n_21));
  MXI2XL g3416__5115(.A (count[13]), .B (n_198), .S0 (start), .Y
       (n_20));
  MXI2XL g3417__7482(.A (count[14]), .B (n_197), .S0 (start), .Y
       (n_19));
  MXI2XL g3418__4733(.A (count[21]), .B (n_190), .S0 (start), .Y
       (n_18));
  MXI2XL g3419__6161(.A (count[15]), .B (n_196), .S0 (start), .Y
       (n_17));
  MXI2XL g3420__9315(.A (count[16]), .B (n_195), .S0 (start), .Y
       (n_16));
  MXI2XL g3421__9945(.A (count[23]), .B (n_188), .S0 (start), .Y
       (n_15));
  MXI2XL g3422__2883(.A (count[17]), .B (n_194), .S0 (start), .Y
       (n_14));
  MXI2XL g3423__2346(.A (count[18]), .B (n_193), .S0 (start), .Y
       (n_13));
  MXI2XL g3424__1666(.A (count[19]), .B (n_192), .S0 (start), .Y
       (n_12));
  MXI2XL g3425__7410(.A (count[20]), .B (n_191), .S0 (start), .Y
       (n_11));
  MXI2XL g3426__6417(.A (count[22]), .B (n_189), .S0 (start), .Y
       (n_10));
  MXI2XL g3427__5477(.A (count[24]), .B (n_187), .S0 (start), .Y (n_9));
  MXI2XL g3428__2398(.A (count[25]), .B (n_186), .S0 (start), .Y (n_8));
  NOR2XL g3430__5107(.A (count[13]), .B (count[20]), .Y (n_6));
  NOR2XL g3431__6260(.A (count[2]), .B (count[1]), .Y (n_7));
  CLKINVX1 g3433(.A (count[3]), .Y (n_5));
  INVX1 g3434(.A (count[4]), .Y (n_4));
  CLKINVX1 g3436(.A (reset), .Y (n_3));
  NOR2BX1 g2__4319(.AN (n_98), .B (master_rd_wr), .Y (n_2));
  NOR2BX1 g3437__8428(.AN (start), .B (count[31]), .Y (n_1));
  NAND2BX1 g3438__5526(.AN (master_rd_wr), .B (n_93), .Y (n_0));
  OAI21XL inc_add_88_20_g407__6783(.A0 (count[31]), .A1
       (inc_add_88_20_n_256), .B0 (inc_add_88_20_n_251), .Y (n_180));
  NAND2XL inc_add_88_20_g408__3680(.A (inc_add_88_20_n_256), .B
       (count[31]), .Y (inc_add_88_20_n_251));
  OA21X1 inc_add_88_20_g409__1617(.A0 (inc_add_88_20_n_264), .A1
       (count[30]), .B0 (inc_add_88_20_n_256), .Y (n_181));
  NAND2XL inc_add_88_20_g410__2802(.A (inc_add_88_20_n_264), .B
       (count[30]), .Y (inc_add_88_20_n_256));
  OAI21XL inc_add_88_20_g411__1705(.A0 (count[29]), .A1
       (inc_add_88_20_n_267), .B0 (inc_add_88_20_n_261), .Y (n_182));
  NAND2XL inc_add_88_20_g412__5122(.A (inc_add_88_20_n_267), .B
       (count[29]), .Y (inc_add_88_20_n_261));
  NOR2BXL inc_add_88_20_g413__8246(.AN (count[29]), .B
       (inc_add_88_20_n_267), .Y (inc_add_88_20_n_264));
  OA21X1 inc_add_88_20_g414__7098(.A0 (inc_add_88_20_n_276), .A1
       (count[28]), .B0 (inc_add_88_20_n_267), .Y (n_183));
  NAND2XL inc_add_88_20_g415__6131(.A (inc_add_88_20_n_276), .B
       (count[28]), .Y (inc_add_88_20_n_267));
  OAI21XL inc_add_88_20_g416__1881(.A0 (count[27]), .A1
       (inc_add_88_20_n_279), .B0 (inc_add_88_20_n_273), .Y (n_184));
  NAND2XL inc_add_88_20_g417__5115(.A (inc_add_88_20_n_279), .B
       (count[27]), .Y (inc_add_88_20_n_273));
  NOR2BXL inc_add_88_20_g418__7482(.AN (count[27]), .B
       (inc_add_88_20_n_279), .Y (inc_add_88_20_n_276));
  OA21X1 inc_add_88_20_g419__4733(.A0 (inc_add_88_20_n_285), .A1
       (count[26]), .B0 (inc_add_88_20_n_279), .Y (n_185));
  NAND2XL inc_add_88_20_g420__6161(.A (inc_add_88_20_n_285), .B
       (count[26]), .Y (inc_add_88_20_n_279));
  AOI2BB1XL inc_add_88_20_g421__9315(.A0N (inc_add_88_20_n_290), .A1N
       (count[25]), .B0 (inc_add_88_20_n_285), .Y (n_186));
  AND2X1 inc_add_88_20_g422__9945(.A (inc_add_88_20_n_290), .B
       (count[25]), .Y (inc_add_88_20_n_285));
  AOI21XL inc_add_88_20_g423__2883(.A0 (inc_add_88_20_n_295), .A1
       (inc_add_88_20_n_426), .B0 (inc_add_88_20_n_290), .Y (n_187));
  NOR2XL inc_add_88_20_g424__2346(.A (inc_add_88_20_n_295), .B
       (inc_add_88_20_n_426), .Y (inc_add_88_20_n_290));
  OAI21XL inc_add_88_20_g425__1666(.A0 (count[23]), .A1
       (inc_add_88_20_n_301), .B0 (inc_add_88_20_n_298), .Y (n_188));
  NAND2BXL inc_add_88_20_g426__7410(.AN (inc_add_88_20_n_301), .B
       (count[23]), .Y (inc_add_88_20_n_295));
  NAND2XL inc_add_88_20_g427__6417(.A (inc_add_88_20_n_301), .B
       (count[23]), .Y (inc_add_88_20_n_298));
  OA21X1 inc_add_88_20_g428__5477(.A0 (inc_add_88_20_n_307), .A1
       (count[22]), .B0 (inc_add_88_20_n_301), .Y (n_189));
  NAND2XL inc_add_88_20_g429__2398(.A (inc_add_88_20_n_307), .B
       (count[22]), .Y (inc_add_88_20_n_301));
  AOI2BB1XL inc_add_88_20_g430__5107(.A0N (inc_add_88_20_n_315), .A1N
       (count[21]), .B0 (inc_add_88_20_n_307), .Y (n_190));
  AND2X1 inc_add_88_20_g431__6260(.A (inc_add_88_20_n_315), .B
       (count[21]), .Y (inc_add_88_20_n_307));
  OAI21XL inc_add_88_20_g432__4319(.A0 (count[20]), .A1
       (inc_add_88_20_n_318), .B0 (inc_add_88_20_n_312), .Y (n_191));
  NAND2XL inc_add_88_20_g433__8428(.A (inc_add_88_20_n_318), .B
       (count[20]), .Y (inc_add_88_20_n_312));
  NOR2BXL inc_add_88_20_g434__5526(.AN (count[20]), .B
       (inc_add_88_20_n_318), .Y (inc_add_88_20_n_315));
  OA21X1 inc_add_88_20_g435__6783(.A0 (inc_add_88_20_n_324), .A1
       (count[19]), .B0 (inc_add_88_20_n_318), .Y (n_192));
  NAND2XL inc_add_88_20_g436__3680(.A (inc_add_88_20_n_324), .B
       (count[19]), .Y (inc_add_88_20_n_318));
  AOI21XL inc_add_88_20_g437__1617(.A0 (inc_add_88_20_n_332), .A1
       (inc_add_88_20_n_445), .B0 (inc_add_88_20_n_324), .Y (n_193));
  NOR2XL inc_add_88_20_g438__2802(.A (inc_add_88_20_n_332), .B
       (inc_add_88_20_n_445), .Y (inc_add_88_20_n_324));
  OAI21XL inc_add_88_20_g439__1705(.A0 (count[17]), .A1
       (inc_add_88_20_n_335), .B0 (inc_add_88_20_n_329), .Y (n_194));
  NAND2XL inc_add_88_20_g440__5122(.A (inc_add_88_20_n_335), .B
       (count[17]), .Y (inc_add_88_20_n_329));
  NAND2BXL inc_add_88_20_g441__8246(.AN (inc_add_88_20_n_335), .B
       (count[17]), .Y (inc_add_88_20_n_332));
  OAI21XL inc_add_88_20_g442__7098(.A0 (count[16]), .A1
       (inc_add_88_20_n_341), .B0 (inc_add_88_20_n_338), .Y (n_195));
  NAND2BXL inc_add_88_20_g443__6131(.AN (inc_add_88_20_n_341), .B
       (count[16]), .Y (inc_add_88_20_n_335));
  NAND2XL inc_add_88_20_g444__1881(.A (inc_add_88_20_n_341), .B
       (count[16]), .Y (inc_add_88_20_n_338));
  OA21X1 inc_add_88_20_g445__5115(.A0 (inc_add_88_20_n_347), .A1
       (count[15]), .B0 (inc_add_88_20_n_341), .Y (n_196));
  NAND2XL inc_add_88_20_g446__7482(.A (inc_add_88_20_n_347), .B
       (count[15]), .Y (inc_add_88_20_n_341));
  AOI21XL inc_add_88_20_g447__4733(.A0 (inc_add_88_20_n_352), .A1
       (inc_add_88_20_n_425), .B0 (inc_add_88_20_n_347), .Y (n_197));
  NOR2XL inc_add_88_20_g448__6161(.A (inc_add_88_20_n_352), .B
       (inc_add_88_20_n_425), .Y (inc_add_88_20_n_347));
  OAI21XL inc_add_88_20_g449__9315(.A0 (count[13]), .A1
       (inc_add_88_20_n_358), .B0 (inc_add_88_20_n_355), .Y (n_198));
  NAND2BXL inc_add_88_20_g450__9945(.AN (inc_add_88_20_n_358), .B
       (count[13]), .Y (inc_add_88_20_n_352));
  NAND2XL inc_add_88_20_g451__2883(.A (inc_add_88_20_n_358), .B
       (count[13]), .Y (inc_add_88_20_n_355));
  OA21X1 inc_add_88_20_g452__2346(.A0 (inc_add_88_20_n_362), .A1
       (count[12]), .B0 (inc_add_88_20_n_358), .Y (n_199));
  NAND2XL inc_add_88_20_g453__1666(.A (inc_add_88_20_n_362), .B
       (count[12]), .Y (inc_add_88_20_n_358));
  ADDHXL inc_add_88_20_g454__7410(.A (inc_add_88_20_n_366), .B
       (count[11]), .CO (inc_add_88_20_n_362), .S (n_200));
  AOI21XL inc_add_88_20_g455__6417(.A0 (inc_add_88_20_n_371), .A1
       (inc_add_88_20_n_422), .B0 (inc_add_88_20_n_366), .Y (n_201));
  NOR2XL inc_add_88_20_g456__5477(.A (inc_add_88_20_n_371), .B
       (inc_add_88_20_n_422), .Y (inc_add_88_20_n_366));
  OA21X1 inc_add_88_20_g457__2398(.A0 (inc_add_88_20_n_379), .A1
       (count[9]), .B0 (inc_add_88_20_n_371), .Y (n_202));
  NAND2XL inc_add_88_20_g458__5107(.A (inc_add_88_20_n_379), .B
       (count[9]), .Y (inc_add_88_20_n_371));
  OAI21XL inc_add_88_20_g459__6260(.A0 (count[8]), .A1
       (inc_add_88_20_n_382), .B0 (inc_add_88_20_n_376), .Y (n_203));
  NAND2XL inc_add_88_20_g460__4319(.A (inc_add_88_20_n_382), .B
       (count[8]), .Y (inc_add_88_20_n_376));
  NOR2BXL inc_add_88_20_g461__8428(.AN (count[8]), .B
       (inc_add_88_20_n_382), .Y (inc_add_88_20_n_379));
  OA21X1 inc_add_88_20_g462__5526(.A0 (inc_add_88_20_n_388), .A1
       (count[7]), .B0 (inc_add_88_20_n_382), .Y (n_204));
  NAND2XL inc_add_88_20_g463__6783(.A (inc_add_88_20_n_388), .B
       (count[7]), .Y (inc_add_88_20_n_382));
  AOI21XL inc_add_88_20_g464__3680(.A0 (inc_add_88_20_n_396), .A1
       (inc_add_88_20_n_418), .B0 (inc_add_88_20_n_388), .Y (n_205));
  NOR2XL inc_add_88_20_g465__1617(.A (inc_add_88_20_n_396), .B
       (inc_add_88_20_n_418), .Y (inc_add_88_20_n_388));
  OAI21XL inc_add_88_20_g466__2802(.A0 (count[5]), .A1
       (inc_add_88_20_n_399), .B0 (inc_add_88_20_n_393), .Y (n_206));
  NAND2XL inc_add_88_20_g467__1705(.A (inc_add_88_20_n_399), .B
       (count[5]), .Y (inc_add_88_20_n_393));
  NAND2BXL inc_add_88_20_g468__5122(.AN (inc_add_88_20_n_399), .B
       (count[5]), .Y (inc_add_88_20_n_396));
  OA21X1 inc_add_88_20_g469__8246(.A0 (inc_add_88_20_n_405), .A1
       (count[4]), .B0 (inc_add_88_20_n_399), .Y (n_207));
  NAND2XL inc_add_88_20_g470__7098(.A (inc_add_88_20_n_405), .B
       (count[4]), .Y (inc_add_88_20_n_399));
  AOI2BB1XL inc_add_88_20_g471__6131(.A0N (inc_add_88_20_n_410), .A1N
       (count[3]), .B0 (inc_add_88_20_n_405), .Y (n_208));
  AND2X1 inc_add_88_20_g472__1881(.A (inc_add_88_20_n_410), .B
       (count[3]), .Y (inc_add_88_20_n_405));
  AOI21XL inc_add_88_20_g473__5115(.A0 (inc_add_88_20_n_415), .A1
       (inc_add_88_20_n_419), .B0 (inc_add_88_20_n_410), .Y (n_209));
  NOR2XL inc_add_88_20_g474__7482(.A (inc_add_88_20_n_415), .B
       (inc_add_88_20_n_419), .Y (inc_add_88_20_n_410));
  OA21X1 inc_add_88_20_g475__4733(.A0 (count[0]), .A1 (count[1]), .B0
       (inc_add_88_20_n_415), .Y (n_210));
  NAND2XL inc_add_88_20_g476__6161(.A (count[0]), .B (count[1]), .Y
       (inc_add_88_20_n_415));
  CLKINVX1 inc_add_88_20_g477(.A (count[6]), .Y (inc_add_88_20_n_418));
  CLKINVX1 inc_add_88_20_g478(.A (count[2]), .Y (inc_add_88_20_n_419));
  CLKINVX1 inc_add_88_20_g479(.A (count[10]), .Y (inc_add_88_20_n_422));
  CLKINVX1 inc_add_88_20_g480(.A (count[14]), .Y (inc_add_88_20_n_425));
  CLKINVX1 inc_add_88_20_g481(.A (count[24]), .Y (inc_add_88_20_n_426));
  INVX1 inc_add_88_20_g482(.A (count[0]), .Y (n_211));
  CLKINVX1 inc_add_88_20_g483(.A (count[18]), .Y (inc_add_88_20_n_445));
endmodule

module spi_slave(sclk, reset, cs, mosi, miso, slave_rd_wr,
     slave_address, slave_in_data, slave_out_data);
  input sclk, reset, cs, mosi;
  input [7:0] slave_out_data;
  output miso, slave_rd_wr;
  output [6:0] slave_address;
  output [7:0] slave_in_data;
  wire sclk, reset, cs, mosi;
  wire [7:0] slave_out_data;
  wire miso, slave_rd_wr;
  wire [6:0] slave_address;
  wire [7:0] slave_in_data;
  wire [7:0] in_data;
  wire [7:0] in_header;
  wire [31:0] count_s;
  wire [7:0] out_data;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27, UNCONNECTED28, UNCONNECTED29, UNCONNECTED30;
  wire UNCONNECTED31, UNCONNECTED32, UNCONNECTED33, UNCONNECTED34,
       UNCONNECTED35, UNCONNECTED36, UNCONNECTED37, UNCONNECTED38;
  wire UNCONNECTED39, UNCONNECTED40, UNCONNECTED41, UNCONNECTED42,
       UNCONNECTED43, UNCONNECTED44, UNCONNECTED45, UNCONNECTED46;
  wire UNCONNECTED47, UNCONNECTED48, UNCONNECTED49, UNCONNECTED50,
       UNCONNECTED51, UNCONNECTED52, UNCONNECTED53, UNCONNECTED54;
  wire UNCONNECTED55, inc_add_136_24_n_251, inc_add_136_24_n_256,
       inc_add_136_24_n_261, inc_add_136_24_n_264,
       inc_add_136_24_n_267, inc_add_136_24_n_273, inc_add_136_24_n_276;
  wire inc_add_136_24_n_279, inc_add_136_24_n_285,
       inc_add_136_24_n_290, inc_add_136_24_n_295,
       inc_add_136_24_n_298, inc_add_136_24_n_301,
       inc_add_136_24_n_307, inc_add_136_24_n_312;
  wire inc_add_136_24_n_315, inc_add_136_24_n_318,
       inc_add_136_24_n_324, inc_add_136_24_n_329,
       inc_add_136_24_n_332, inc_add_136_24_n_335,
       inc_add_136_24_n_338, inc_add_136_24_n_341;
  wire inc_add_136_24_n_347, inc_add_136_24_n_352,
       inc_add_136_24_n_355, inc_add_136_24_n_358,
       inc_add_136_24_n_362, inc_add_136_24_n_366,
       inc_add_136_24_n_371, inc_add_136_24_n_376;
  wire inc_add_136_24_n_379, inc_add_136_24_n_382,
       inc_add_136_24_n_388, inc_add_136_24_n_393,
       inc_add_136_24_n_396, inc_add_136_24_n_399,
       inc_add_136_24_n_405, inc_add_136_24_n_410;
  wire inc_add_136_24_n_415, inc_add_136_24_n_418,
       inc_add_136_24_n_419, inc_add_136_24_n_422,
       inc_add_136_24_n_425, inc_add_136_24_n_426,
       inc_add_136_24_n_445, n_0;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_89;
  wire n_90, n_91, n_92, n_93, n_94, n_95, n_96, n_97;
  wire n_98, n_99, n_100, n_101, n_102, n_103, n_104, n_105;
  wire n_106, n_107, n_108, n_109, n_154, n_155, n_156, n_157;
  wire n_158, n_159, n_160, n_161, n_162, n_163, n_164, n_165;
  wire n_166, n_167, n_168, n_169, n_170, n_171, n_172, n_173;
  wire n_174, n_175, n_176, n_177, n_178, n_179, n_180, n_181;
  wire n_182, n_183, n_184, n_185;
  assign count_s[31] = 1'b0;
  assign count_s[30] = 1'b0;
  assign count_s[29] = 1'b0;
  assign count_s[28] = 1'b0;
  assign count_s[27] = 1'b0;
  assign count_s[26] = 1'b0;
  assign count_s[25] = 1'b0;
  assign count_s[24] = 1'b0;
  assign count_s[23] = 1'b0;
  assign count_s[22] = 1'b0;
  assign count_s[21] = 1'b0;
  assign count_s[20] = 1'b0;
  assign count_s[19] = 1'b0;
  assign count_s[18] = 1'b0;
  assign count_s[17] = 1'b0;
  assign count_s[16] = 1'b0;
  assign count_s[15] = 1'b0;
  assign count_s[14] = 1'b0;
  assign count_s[13] = 1'b0;
  assign count_s[12] = 1'b0;
  assign count_s[11] = 1'b0;
  assign count_s[10] = 1'b0;
  assign count_s[9] = 1'b0;
  assign count_s[8] = 1'b0;
  assign count_s[7] = 1'b0;
  assign count_s[6] = 1'b0;
  assign count_s[5] = 1'b0;
  assign count_s[4] = 1'b0;
  assign count_s[3] = 1'b0;
  assign count_s[2] = 1'b0;
  assign count_s[1] = 1'b0;
  assign count_s[0] = 1'b0;
  DFFQXL \slave_in_data_reg[0] (.CK (cs), .D (in_data[0]), .Q
       (slave_in_data[0]));
  DFFQXL \slave_address_reg[6] (.CK (cs), .D (in_header[6]), .Q
       (slave_address[6]));
  DFFQXL \slave_address_reg[4] (.CK (cs), .D (in_header[4]), .Q
       (slave_address[4]));
  DFFQXL \slave_address_reg[0] (.CK (cs), .D (in_header[0]), .Q
       (slave_address[0]));
  DFFQXL slave_rd_wr_reg(.CK (cs), .D (in_header[7]), .Q (slave_rd_wr));
  DFFQXL \slave_in_data_reg[7] (.CK (cs), .D (in_data[7]), .Q
       (slave_in_data[7]));
  DFFQXL \slave_address_reg[3] (.CK (cs), .D (in_header[3]), .Q
       (slave_address[3]));
  DFFQXL \slave_in_data_reg[6] (.CK (cs), .D (in_data[6]), .Q
       (slave_in_data[6]));
  DFFQXL \slave_in_data_reg[3] (.CK (cs), .D (in_data[3]), .Q
       (slave_in_data[3]));
  DFFQXL \slave_address_reg[5] (.CK (cs), .D (in_header[5]), .Q
       (slave_address[5]));
  DFFQXL \slave_address_reg[2] (.CK (cs), .D (in_header[2]), .Q
       (slave_address[2]));
  DFFQXL \slave_in_data_reg[4] (.CK (cs), .D (in_data[4]), .Q
       (slave_in_data[4]));
  DFFQXL \slave_in_data_reg[5] (.CK (cs), .D (in_data[5]), .Q
       (slave_in_data[5]));
  DFFQXL \slave_address_reg[1] (.CK (cs), .D (in_header[1]), .Q
       (slave_address[1]));
  DFFQXL \slave_in_data_reg[2] (.CK (cs), .D (in_data[2]), .Q
       (slave_in_data[2]));
  DFFQXL \slave_in_data_reg[1] (.CK (cs), .D (in_data[1]), .Q
       (slave_in_data[1]));
  DFFNSRXL \count_s_reg[0] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_67), .Q (count_s[0]), .QN (UNCONNECTED));
  DFFNSRXL \count_s_reg[1] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_65), .Q (count_s[1]), .QN (UNCONNECTED0));
  DFFNSRXL \count_s_reg[2] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_72), .Q (count_s[2]), .QN (UNCONNECTED1));
  DFFNSRXL \count_s_reg[3] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_69), .Q (count_s[3]), .QN (UNCONNECTED2));
  DFFNSRXL \count_s_reg[4] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_64), .Q (count_s[4]), .QN (UNCONNECTED3));
  DFFNSRXL \count_s_reg[5] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_63), .Q (count_s[5]), .QN (UNCONNECTED4));
  DFFNSRXL \count_s_reg[6] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_61), .Q (count_s[6]), .QN (UNCONNECTED5));
  DFFNSRXL \count_s_reg[7] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_60), .Q (count_s[7]), .QN (UNCONNECTED6));
  DFFNSRXL \count_s_reg[8] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_58), .Q (count_s[8]), .QN (UNCONNECTED7));
  DFFNSRXL \count_s_reg[9] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_59), .Q (count_s[9]), .QN (UNCONNECTED8));
  DFFNSRXL \count_s_reg[10] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_57), .Q (count_s[10]), .QN (UNCONNECTED9));
  DFFNSRXL \count_s_reg[11] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_55), .Q (count_s[11]), .QN (UNCONNECTED10));
  DFFNSRXL \count_s_reg[12] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_54), .Q (count_s[12]), .QN (UNCONNECTED11));
  DFFNSRXL \count_s_reg[13] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_62), .Q (count_s[13]), .QN (UNCONNECTED12));
  DFFNSRXL \count_s_reg[14] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_49), .Q (count_s[14]), .QN (UNCONNECTED13));
  DFFNSRXL \count_s_reg[15] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_53), .Q (count_s[15]), .QN (UNCONNECTED14));
  DFFNSRXL \count_s_reg[16] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_52), .Q (count_s[16]), .QN (UNCONNECTED15));
  DFFNSRXL \count_s_reg[17] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_51), .Q (count_s[17]), .QN (UNCONNECTED16));
  DFFNSRXL \count_s_reg[18] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_50), .Q (count_s[18]), .QN (UNCONNECTED17));
  DFFNSRXL \count_s_reg[19] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_48), .Q (count_s[19]), .QN (UNCONNECTED18));
  DFFNSRXL \count_s_reg[20] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_45), .Q (count_s[20]), .QN (UNCONNECTED19));
  DFFNSRXL \count_s_reg[21] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_47), .Q (count_s[21]), .QN (UNCONNECTED20));
  DFFNSRXL \count_s_reg[22] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_46), .Q (count_s[22]), .QN (UNCONNECTED21));
  DFFNSRXL \count_s_reg[23] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_44), .Q (count_s[23]), .QN (UNCONNECTED22));
  DFFNSRXL \count_s_reg[24] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_43), .Q (count_s[24]), .QN (UNCONNECTED23));
  DFFNSRXL \count_s_reg[25] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_42), .Q (count_s[25]), .QN (UNCONNECTED24));
  DFFNSRXL \count_s_reg[26] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_41), .Q (count_s[26]), .QN (UNCONNECTED25));
  DFFNSRXL \count_s_reg[27] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_73), .Q (count_s[27]), .QN (UNCONNECTED26));
  DFFNSRXL \count_s_reg[28] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_71), .Q (count_s[28]), .QN (UNCONNECTED27));
  DFFNSRXL \count_s_reg[29] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_70), .Q (count_s[29]), .QN (UNCONNECTED28));
  DFFNSRXL \count_s_reg[30] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_68), .Q (count_s[30]), .QN (UNCONNECTED29));
  DFFNSRXL \count_s_reg[31] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_66), .Q (count_s[31]), .QN (UNCONNECTED30));
  SDFFNSRX1 \in_data_reg[0] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (mosi), .SI (in_data[0]), .SE (n_90), .Q (in_data[0]), .QN
       (UNCONNECTED31));
  SDFFNSRX1 \in_data_reg[1] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (in_data[0]), .SI (in_data[1]), .SE (n_90), .Q (in_data[1]), .QN
       (UNCONNECTED32));
  SDFFNSRX1 \in_data_reg[2] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (in_data[1]), .SI (in_data[2]), .SE (n_90), .Q (in_data[2]), .QN
       (UNCONNECTED33));
  SDFFNSRX1 \in_data_reg[3] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (in_data[2]), .SI (in_data[3]), .SE (n_90), .Q (in_data[3]), .QN
       (UNCONNECTED34));
  SDFFNSRX1 \in_data_reg[4] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (in_data[3]), .SI (in_data[4]), .SE (n_90), .Q (in_data[4]), .QN
       (UNCONNECTED35));
  SDFFNSRX1 \in_data_reg[5] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (in_data[4]), .SI (in_data[5]), .SE (n_90), .Q (in_data[5]), .QN
       (UNCONNECTED36));
  SDFFNSRX1 \in_data_reg[6] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (in_data[5]), .SI (in_data[6]), .SE (n_90), .Q (in_data[6]), .QN
       (UNCONNECTED37));
  SDFFNSRX1 \in_data_reg[7] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (in_data[6]), .SI (in_data[7]), .SE (n_90), .Q (in_data[7]), .QN
       (UNCONNECTED38));
  SDFFNSRX1 \in_header_reg[0] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (mosi), .SI (in_header[0]), .SE (n_84), .Q (in_header[0]), .QN
       (UNCONNECTED39));
  SDFFNSRX1 \in_header_reg[1] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (in_header[0]), .SI (in_header[1]), .SE (n_84), .Q
       (in_header[1]), .QN (UNCONNECTED40));
  SDFFNSRX1 \in_header_reg[2] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (in_header[1]), .SI (in_header[2]), .SE (n_84), .Q
       (in_header[2]), .QN (UNCONNECTED41));
  SDFFNSRX1 \in_header_reg[3] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (in_header[2]), .SI (in_header[3]), .SE (n_84), .Q
       (in_header[3]), .QN (UNCONNECTED42));
  SDFFNSRX1 \in_header_reg[4] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (in_header[3]), .SI (in_header[4]), .SE (n_84), .Q
       (in_header[4]), .QN (UNCONNECTED43));
  SDFFNSRX1 \in_header_reg[5] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (in_header[4]), .SI (in_header[5]), .SE (n_84), .Q
       (in_header[5]), .QN (UNCONNECTED44));
  SDFFNSRX1 \in_header_reg[6] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (in_header[5]), .SI (in_header[6]), .SE (n_84), .Q
       (in_header[6]), .QN (UNCONNECTED45));
  SDFFNSRX1 \in_header_reg[7] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (in_header[6]), .SI (in_header[7]), .SE (n_84), .Q
       (in_header[7]), .QN (UNCONNECTED46));
  DFFNSRXL miso_reg(.RN (1'b1), .SN (1'b1), .CKN (sclk), .D (n_95), .Q
       (miso), .QN (UNCONNECTED47));
  DFFNSRXL \out_data_reg[0] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_94), .Q (out_data[0]), .QN (UNCONNECTED48));
  DFFNSRXL \out_data_reg[1] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_107), .Q (out_data[1]), .QN (UNCONNECTED49));
  DFFNSRXL \out_data_reg[2] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_106), .Q (out_data[2]), .QN (UNCONNECTED50));
  DFFNSRXL \out_data_reg[3] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_105), .Q (out_data[3]), .QN (UNCONNECTED51));
  DFFNSRXL \out_data_reg[4] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_104), .Q (out_data[4]), .QN (UNCONNECTED52));
  DFFNSRXL \out_data_reg[5] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_103), .Q (out_data[5]), .QN (UNCONNECTED53));
  DFFNSRXL \out_data_reg[6] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_108), .Q (out_data[6]), .QN (UNCONNECTED54));
  DFFNSRXL \out_data_reg[7] (.RN (1'b1), .SN (1'b1), .CKN (sclk), .D
       (n_109), .Q (out_data[7]), .QN (UNCONNECTED55));
  INVXL g2257(.A (n_102), .Y (n_109));
  INVXL g2258(.A (n_101), .Y (n_108));
  INVXL g2259(.A (n_100), .Y (n_107));
  INVXL g2260(.A (n_99), .Y (n_106));
  INVXL g2261(.A (n_98), .Y (n_105));
  INVXL g2262(.A (n_97), .Y (n_104));
  INVXL g2263(.A (n_96), .Y (n_103));
  AOI222XL g2264__9315(.A0 (n_92), .A1 (out_data[6]), .B0
       (out_data[7]), .B1 (n_91), .C0 (n_0), .C1 (slave_out_data[7]),
       .Y (n_102));
  AOI222XL g2265__9945(.A0 (n_92), .A1 (out_data[5]), .B0
       (out_data[6]), .B1 (n_91), .C0 (n_0), .C1 (slave_out_data[6]),
       .Y (n_101));
  AOI222XL g2266__2883(.A0 (n_92), .A1 (out_data[0]), .B0
       (out_data[1]), .B1 (n_91), .C0 (n_0), .C1 (slave_out_data[1]),
       .Y (n_100));
  AOI222XL g2267__2346(.A0 (n_92), .A1 (out_data[1]), .B0
       (out_data[2]), .B1 (n_91), .C0 (n_0), .C1 (slave_out_data[2]),
       .Y (n_99));
  AOI222XL g2268__1666(.A0 (n_92), .A1 (out_data[2]), .B0
       (out_data[3]), .B1 (n_91), .C0 (n_0), .C1 (slave_out_data[3]),
       .Y (n_98));
  AOI222XL g2269__7410(.A0 (n_92), .A1 (out_data[3]), .B0
       (out_data[4]), .B1 (n_91), .C0 (n_0), .C1 (slave_out_data[4]),
       .Y (n_97));
  AOI222XL g2270__6417(.A0 (n_92), .A1 (out_data[4]), .B0
       (out_data[5]), .B1 (n_91), .C0 (n_0), .C1 (slave_out_data[5]),
       .Y (n_96));
  NOR2XL g2273__5477(.A (n_2), .B (n_93), .Y (n_95));
  AO22X1 g2274__2398(.A0 (out_data[0]), .A1 (n_91), .B0
       (slave_out_data[0]), .B1 (n_0), .Y (n_94));
  MXI2XL g2275__5107(.A (miso), .B (out_data[7]), .S0 (n_89), .Y
       (n_93));
  NOR2BXL g2276__6260(.AN (n_89), .B (n_2), .Y (n_92));
  OAI2BB1XL g2277__4319(.A0N (n_88), .A1N (n_4), .B0 (reset), .Y
       (n_91));
  OR4X1 g2278__8428(.A (n_87), .B (n_2), .C (cs), .D (in_header[7]), .Y
       (n_90));
  NOR2XL g2279__5526(.A (n_88), .B (cs), .Y (n_89));
  NAND2BXL g2280__6783(.AN (n_87), .B (in_header[7]), .Y (n_88));
  OR4X1 g2281__3680(.A (n_86), .B (count_s[14]), .C (count_s[17]), .D
       (count_s[16]), .Y (n_87));
  OR4X1 g2282__1617(.A (n_85), .B (count_s[20]), .C (count_s[21]), .D
       (count_s[15]), .Y (n_86));
  OR4X1 g2287__2802(.A (n_83), .B (count_s[5]), .C (count_s[12]), .D
       (count_s[13]), .Y (n_85));
  NAND2XL g2292__1705(.A (reset), .B (n_82), .Y (n_84));
  OR4X1 g2293__5122(.A (n_81), .B (count_s[23]), .C (count_s[22]), .D
       (count_s[4]), .Y (n_83));
  NOR4BXL g2294__8246(.AN (n_39), .B (n_80), .C (count_s[31]), .D (cs),
       .Y (n_82));
  NAND3XL g2295__7098(.A (n_76), .B (n_39), .C (n_80), .Y (n_81));
  NAND2XL g2296__6131(.A (n_79), .B (n_56), .Y (n_80));
  NOR4BXL g2297__1881(.AN (n_78), .B (count_s[16]), .C (count_s[22]),
       .D (count_s[23]), .Y (n_79));
  NOR4XL g2298__5115(.A (n_77), .B (count_s[20]), .C (count_s[21]), .D
       (count_s[17]), .Y (n_78));
  AOI31XL g2299__7482(.A0 (n_3), .A1 (n_74), .A2 (n_75), .B0
       (count_s[31]), .Y (n_77));
  AND3XL g2300__4733(.A (n_56), .B (n_74), .C (n_3), .Y (n_76));
  NOR4BXL g2301__6161(.AN (n_40), .B (count_s[4]), .C (count_s[15]), .D
       (count_s[14]), .Y (n_75));
  NOR4BXL g2334__9315(.AN (n_5), .B (count_s[8]), .C (count_s[9]), .D
       (count_s[10]), .Y (n_74));
  NOR2XL g2335__9945(.A (n_2), .B (n_36), .Y (n_73));
  NOR2XL g2336__2883(.A (n_2), .B (n_33), .Y (n_72));
  NOR2XL g2337__2346(.A (n_2), .B (n_34), .Y (n_71));
  NOR2XL g2338__1666(.A (n_2), .B (n_32), .Y (n_70));
  NOR2XL g2339__7410(.A (n_2), .B (n_29), .Y (n_69));
  NOR2XL g2340__6417(.A (n_2), .B (n_31), .Y (n_68));
  NOR2XL g2341__5477(.A (n_2), .B (n_20), .Y (n_67));
  NOR2XL g2342__2398(.A (n_2), .B (n_30), .Y (n_66));
  NOR2XL g2343__5107(.A (n_2), .B (n_35), .Y (n_65));
  NOR2XL g2344__6260(.A (n_2), .B (n_28), .Y (n_64));
  NOR2XL g2345__4319(.A (n_2), .B (n_27), .Y (n_63));
  NOR2XL g2346__8428(.A (n_2), .B (n_19), .Y (n_62));
  NOR2XL g2347__5526(.A (n_2), .B (n_37), .Y (n_61));
  NOR2XL g2348__6783(.A (n_2), .B (n_26), .Y (n_60));
  NOR2XL g2349__3680(.A (n_2), .B (n_24), .Y (n_59));
  NOR2XL g2350__1617(.A (n_2), .B (n_25), .Y (n_58));
  NOR2XL g2351__2802(.A (n_2), .B (n_38), .Y (n_57));
  NOR2XL g2352__1705(.A (n_2), .B (n_22), .Y (n_55));
  NOR2XL g2353__5122(.A (n_2), .B (n_21), .Y (n_54));
  NOR2XL g2354__8246(.A (n_2), .B (n_18), .Y (n_53));
  NOR2XL g2355__7098(.A (n_2), .B (n_16), .Y (n_52));
  NOR2XL g2356__6131(.A (n_2), .B (n_15), .Y (n_51));
  NOR2XL g2357__1881(.A (n_2), .B (n_14), .Y (n_50));
  NOR2XL g2358__5115(.A (n_2), .B (n_17), .Y (n_49));
  NOR2XL g2359__7482(.A (n_2), .B (n_12), .Y (n_48));
  NOR2XL g2360__4733(.A (n_2), .B (n_13), .Y (n_47));
  NOR2XL g2361__6161(.A (n_2), .B (n_10), .Y (n_46));
  NOR2XL g2362__9315(.A (n_2), .B (n_11), .Y (n_45));
  NOR2XL g2363__9945(.A (n_2), .B (n_9), .Y (n_44));
  NOR2XL g2364__2883(.A (n_2), .B (n_8), .Y (n_43));
  NOR2XL g2365__2346(.A (n_2), .B (n_7), .Y (n_42));
  NOR2XL g2366__1666(.A (n_2), .B (n_6), .Y (n_41));
  NOR4XL g2367__7410(.A (count_s[12]), .B (count_s[3]), .C
       (count_s[13]), .D (count_s[5]), .Y (n_40));
  NOR3XL g2368__6417(.A (count_s[24]), .B (count_s[25]), .C (n_23), .Y
       (n_56));
  MXI2XL g2369__5477(.A (n_175), .B (count_s[10]), .S0 (cs), .Y (n_38));
  MXI2XL g2370__2398(.A (n_179), .B (count_s[6]), .S0 (cs), .Y (n_37));
  MXI2XL g2371__5107(.A (n_158), .B (count_s[27]), .S0 (cs), .Y (n_36));
  MXI2XL g2372__6260(.A (n_184), .B (count_s[1]), .S0 (cs), .Y (n_35));
  MXI2XL g2373__4319(.A (n_157), .B (count_s[28]), .S0 (cs), .Y (n_34));
  MXI2XL g2374__8428(.A (n_183), .B (count_s[2]), .S0 (cs), .Y (n_33));
  MXI2XL g2375__5526(.A (n_156), .B (count_s[29]), .S0 (cs), .Y (n_32));
  MXI2XL g2376__6783(.A (n_155), .B (count_s[30]), .S0 (cs), .Y (n_31));
  MXI2XL g2377__3680(.A (n_154), .B (count_s[31]), .S0 (cs), .Y (n_30));
  MXI2XL g2378__1617(.A (n_182), .B (count_s[3]), .S0 (cs), .Y (n_29));
  MXI2XL g2379__2802(.A (n_181), .B (count_s[4]), .S0 (cs), .Y (n_28));
  MXI2XL g2380__1705(.A (n_180), .B (count_s[5]), .S0 (cs), .Y (n_27));
  MXI2XL g2381__5122(.A (n_178), .B (count_s[7]), .S0 (cs), .Y (n_26));
  MXI2XL g2382__8246(.A (n_177), .B (count_s[8]), .S0 (cs), .Y (n_25));
  MXI2XL g2383__7098(.A (n_176), .B (count_s[9]), .S0 (cs), .Y (n_24));
  OR4X1 g2384__6131(.A (count_s[28]), .B (count_s[29]), .C
       (count_s[18]), .D (count_s[19]), .Y (n_23));
  NOR3XL g2385__1881(.A (count_s[27]), .B (count_s[30]), .C
       (count_s[26]), .Y (n_39));
  MXI2XL g2386__5115(.A (n_174), .B (count_s[11]), .S0 (cs), .Y (n_22));
  MXI2XL g2387__7482(.A (n_173), .B (count_s[12]), .S0 (cs), .Y (n_21));
  MXI2XL g2388__4733(.A (n_185), .B (count_s[0]), .S0 (cs), .Y (n_20));
  MXI2XL g2389__6161(.A (n_172), .B (count_s[13]), .S0 (cs), .Y (n_19));
  MXI2XL g2390__9315(.A (n_170), .B (count_s[15]), .S0 (cs), .Y (n_18));
  MXI2XL g2391__9945(.A (n_171), .B (count_s[14]), .S0 (cs), .Y (n_17));
  MXI2XL g2392__2883(.A (n_169), .B (count_s[16]), .S0 (cs), .Y (n_16));
  MXI2XL g2393__2346(.A (n_168), .B (count_s[17]), .S0 (cs), .Y (n_15));
  MXI2XL g2394__1666(.A (n_167), .B (count_s[18]), .S0 (cs), .Y (n_14));
  MXI2XL g2395__7410(.A (n_164), .B (count_s[21]), .S0 (cs), .Y (n_13));
  MXI2XL g2396__6417(.A (n_166), .B (count_s[19]), .S0 (cs), .Y (n_12));
  MXI2XL g2397__5477(.A (n_165), .B (count_s[20]), .S0 (cs), .Y (n_11));
  MXI2XL g2398__2398(.A (n_163), .B (count_s[22]), .S0 (cs), .Y (n_10));
  MXI2XL g2399__5107(.A (n_162), .B (count_s[23]), .S0 (cs), .Y (n_9));
  MXI2XL g2400__6260(.A (n_161), .B (count_s[24]), .S0 (cs), .Y (n_8));
  MXI2XL g2401__4319(.A (n_160), .B (count_s[25]), .S0 (cs), .Y (n_7));
  MXI2XL g2402__8428(.A (n_159), .B (count_s[26]), .S0 (cs), .Y (n_6));
  NOR2XL g2403__5526(.A (count_s[6]), .B (count_s[7]), .Y (n_5));
  INVX1 g2404(.A (n_0), .Y (n_4));
  CLKINVX1 g2407(.A (count_s[11]), .Y (n_3));
  CLKINVX1 g2408(.A (reset), .Y (n_2));
  NOR2BX1 g2__6783(.AN (cs), .B (n_2), .Y (n_0));
  OAI21XL inc_add_136_24_g407__3680(.A0 (count_s[31]), .A1
       (inc_add_136_24_n_256), .B0 (inc_add_136_24_n_251), .Y (n_154));
  NAND2XL inc_add_136_24_g408__1617(.A (inc_add_136_24_n_256), .B
       (count_s[31]), .Y (inc_add_136_24_n_251));
  OA21X1 inc_add_136_24_g409__2802(.A0 (inc_add_136_24_n_264), .A1
       (count_s[30]), .B0 (inc_add_136_24_n_256), .Y (n_155));
  NAND2XL inc_add_136_24_g410__1705(.A (inc_add_136_24_n_264), .B
       (count_s[30]), .Y (inc_add_136_24_n_256));
  OAI21XL inc_add_136_24_g411__5122(.A0 (count_s[29]), .A1
       (inc_add_136_24_n_267), .B0 (inc_add_136_24_n_261), .Y (n_156));
  NAND2XL inc_add_136_24_g412__8246(.A (inc_add_136_24_n_267), .B
       (count_s[29]), .Y (inc_add_136_24_n_261));
  NOR2BXL inc_add_136_24_g413__7098(.AN (count_s[29]), .B
       (inc_add_136_24_n_267), .Y (inc_add_136_24_n_264));
  OA21X1 inc_add_136_24_g414__6131(.A0 (inc_add_136_24_n_276), .A1
       (count_s[28]), .B0 (inc_add_136_24_n_267), .Y (n_157));
  NAND2XL inc_add_136_24_g415__1881(.A (inc_add_136_24_n_276), .B
       (count_s[28]), .Y (inc_add_136_24_n_267));
  OAI21XL inc_add_136_24_g416__5115(.A0 (count_s[27]), .A1
       (inc_add_136_24_n_279), .B0 (inc_add_136_24_n_273), .Y (n_158));
  NAND2XL inc_add_136_24_g417__7482(.A (inc_add_136_24_n_279), .B
       (count_s[27]), .Y (inc_add_136_24_n_273));
  NOR2BXL inc_add_136_24_g418__4733(.AN (count_s[27]), .B
       (inc_add_136_24_n_279), .Y (inc_add_136_24_n_276));
  OA21X1 inc_add_136_24_g419__6161(.A0 (inc_add_136_24_n_285), .A1
       (count_s[26]), .B0 (inc_add_136_24_n_279), .Y (n_159));
  NAND2XL inc_add_136_24_g420__9315(.A (inc_add_136_24_n_285), .B
       (count_s[26]), .Y (inc_add_136_24_n_279));
  AOI2BB1XL inc_add_136_24_g421__9945(.A0N (inc_add_136_24_n_290), .A1N
       (count_s[25]), .B0 (inc_add_136_24_n_285), .Y (n_160));
  AND2X1 inc_add_136_24_g422__2883(.A (inc_add_136_24_n_290), .B
       (count_s[25]), .Y (inc_add_136_24_n_285));
  AOI21XL inc_add_136_24_g423__2346(.A0 (inc_add_136_24_n_295), .A1
       (inc_add_136_24_n_426), .B0 (inc_add_136_24_n_290), .Y (n_161));
  NOR2XL inc_add_136_24_g424__1666(.A (inc_add_136_24_n_295), .B
       (inc_add_136_24_n_426), .Y (inc_add_136_24_n_290));
  OAI21XL inc_add_136_24_g425__7410(.A0 (count_s[23]), .A1
       (inc_add_136_24_n_301), .B0 (inc_add_136_24_n_298), .Y (n_162));
  NAND2BXL inc_add_136_24_g426__6417(.AN (inc_add_136_24_n_301), .B
       (count_s[23]), .Y (inc_add_136_24_n_295));
  NAND2XL inc_add_136_24_g427__5477(.A (inc_add_136_24_n_301), .B
       (count_s[23]), .Y (inc_add_136_24_n_298));
  OA21X1 inc_add_136_24_g428__2398(.A0 (inc_add_136_24_n_307), .A1
       (count_s[22]), .B0 (inc_add_136_24_n_301), .Y (n_163));
  NAND2XL inc_add_136_24_g429__5107(.A (inc_add_136_24_n_307), .B
       (count_s[22]), .Y (inc_add_136_24_n_301));
  AOI2BB1XL inc_add_136_24_g430__6260(.A0N (inc_add_136_24_n_315), .A1N
       (count_s[21]), .B0 (inc_add_136_24_n_307), .Y (n_164));
  AND2X1 inc_add_136_24_g431__4319(.A (inc_add_136_24_n_315), .B
       (count_s[21]), .Y (inc_add_136_24_n_307));
  OAI21XL inc_add_136_24_g432__8428(.A0 (count_s[20]), .A1
       (inc_add_136_24_n_318), .B0 (inc_add_136_24_n_312), .Y (n_165));
  NAND2XL inc_add_136_24_g433__5526(.A (inc_add_136_24_n_318), .B
       (count_s[20]), .Y (inc_add_136_24_n_312));
  NOR2BXL inc_add_136_24_g434__6783(.AN (count_s[20]), .B
       (inc_add_136_24_n_318), .Y (inc_add_136_24_n_315));
  OA21X1 inc_add_136_24_g435__3680(.A0 (inc_add_136_24_n_324), .A1
       (count_s[19]), .B0 (inc_add_136_24_n_318), .Y (n_166));
  NAND2XL inc_add_136_24_g436__1617(.A (inc_add_136_24_n_324), .B
       (count_s[19]), .Y (inc_add_136_24_n_318));
  AOI21XL inc_add_136_24_g437__2802(.A0 (inc_add_136_24_n_332), .A1
       (inc_add_136_24_n_445), .B0 (inc_add_136_24_n_324), .Y (n_167));
  NOR2XL inc_add_136_24_g438__1705(.A (inc_add_136_24_n_332), .B
       (inc_add_136_24_n_445), .Y (inc_add_136_24_n_324));
  OAI21XL inc_add_136_24_g439__5122(.A0 (count_s[17]), .A1
       (inc_add_136_24_n_335), .B0 (inc_add_136_24_n_329), .Y (n_168));
  NAND2XL inc_add_136_24_g440__8246(.A (inc_add_136_24_n_335), .B
       (count_s[17]), .Y (inc_add_136_24_n_329));
  NAND2BXL inc_add_136_24_g441__7098(.AN (inc_add_136_24_n_335), .B
       (count_s[17]), .Y (inc_add_136_24_n_332));
  OAI21XL inc_add_136_24_g442__6131(.A0 (count_s[16]), .A1
       (inc_add_136_24_n_341), .B0 (inc_add_136_24_n_338), .Y (n_169));
  NAND2BXL inc_add_136_24_g443__1881(.AN (inc_add_136_24_n_341), .B
       (count_s[16]), .Y (inc_add_136_24_n_335));
  NAND2XL inc_add_136_24_g444__5115(.A (inc_add_136_24_n_341), .B
       (count_s[16]), .Y (inc_add_136_24_n_338));
  OA21X1 inc_add_136_24_g445__7482(.A0 (inc_add_136_24_n_347), .A1
       (count_s[15]), .B0 (inc_add_136_24_n_341), .Y (n_170));
  NAND2XL inc_add_136_24_g446__4733(.A (inc_add_136_24_n_347), .B
       (count_s[15]), .Y (inc_add_136_24_n_341));
  AOI21XL inc_add_136_24_g447__6161(.A0 (inc_add_136_24_n_352), .A1
       (inc_add_136_24_n_425), .B0 (inc_add_136_24_n_347), .Y (n_171));
  NOR2XL inc_add_136_24_g448__9315(.A (inc_add_136_24_n_352), .B
       (inc_add_136_24_n_425), .Y (inc_add_136_24_n_347));
  OAI21XL inc_add_136_24_g449__9945(.A0 (count_s[13]), .A1
       (inc_add_136_24_n_358), .B0 (inc_add_136_24_n_355), .Y (n_172));
  NAND2BXL inc_add_136_24_g450__2883(.AN (inc_add_136_24_n_358), .B
       (count_s[13]), .Y (inc_add_136_24_n_352));
  NAND2XL inc_add_136_24_g451__2346(.A (inc_add_136_24_n_358), .B
       (count_s[13]), .Y (inc_add_136_24_n_355));
  OA21X1 inc_add_136_24_g452__1666(.A0 (inc_add_136_24_n_362), .A1
       (count_s[12]), .B0 (inc_add_136_24_n_358), .Y (n_173));
  NAND2XL inc_add_136_24_g453__7410(.A (inc_add_136_24_n_362), .B
       (count_s[12]), .Y (inc_add_136_24_n_358));
  ADDHXL inc_add_136_24_g454__6417(.A (inc_add_136_24_n_366), .B
       (count_s[11]), .CO (inc_add_136_24_n_362), .S (n_174));
  AOI21XL inc_add_136_24_g455__5477(.A0 (inc_add_136_24_n_371), .A1
       (inc_add_136_24_n_422), .B0 (inc_add_136_24_n_366), .Y (n_175));
  NOR2XL inc_add_136_24_g456__2398(.A (inc_add_136_24_n_371), .B
       (inc_add_136_24_n_422), .Y (inc_add_136_24_n_366));
  OA21X1 inc_add_136_24_g457__5107(.A0 (inc_add_136_24_n_379), .A1
       (count_s[9]), .B0 (inc_add_136_24_n_371), .Y (n_176));
  NAND2XL inc_add_136_24_g458__6260(.A (inc_add_136_24_n_379), .B
       (count_s[9]), .Y (inc_add_136_24_n_371));
  OAI21XL inc_add_136_24_g459__4319(.A0 (count_s[8]), .A1
       (inc_add_136_24_n_382), .B0 (inc_add_136_24_n_376), .Y (n_177));
  NAND2XL inc_add_136_24_g460__8428(.A (inc_add_136_24_n_382), .B
       (count_s[8]), .Y (inc_add_136_24_n_376));
  NOR2BXL inc_add_136_24_g461__5526(.AN (count_s[8]), .B
       (inc_add_136_24_n_382), .Y (inc_add_136_24_n_379));
  OA21X1 inc_add_136_24_g462__6783(.A0 (inc_add_136_24_n_388), .A1
       (count_s[7]), .B0 (inc_add_136_24_n_382), .Y (n_178));
  NAND2XL inc_add_136_24_g463__3680(.A (inc_add_136_24_n_388), .B
       (count_s[7]), .Y (inc_add_136_24_n_382));
  AOI21XL inc_add_136_24_g464__1617(.A0 (inc_add_136_24_n_396), .A1
       (inc_add_136_24_n_418), .B0 (inc_add_136_24_n_388), .Y (n_179));
  NOR2XL inc_add_136_24_g465__2802(.A (inc_add_136_24_n_396), .B
       (inc_add_136_24_n_418), .Y (inc_add_136_24_n_388));
  OAI21XL inc_add_136_24_g466__1705(.A0 (count_s[5]), .A1
       (inc_add_136_24_n_399), .B0 (inc_add_136_24_n_393), .Y (n_180));
  NAND2XL inc_add_136_24_g467__5122(.A (inc_add_136_24_n_399), .B
       (count_s[5]), .Y (inc_add_136_24_n_393));
  NAND2BXL inc_add_136_24_g468__8246(.AN (inc_add_136_24_n_399), .B
       (count_s[5]), .Y (inc_add_136_24_n_396));
  OA21X1 inc_add_136_24_g469__7098(.A0 (inc_add_136_24_n_405), .A1
       (count_s[4]), .B0 (inc_add_136_24_n_399), .Y (n_181));
  NAND2XL inc_add_136_24_g470__6131(.A (inc_add_136_24_n_405), .B
       (count_s[4]), .Y (inc_add_136_24_n_399));
  AOI2BB1XL inc_add_136_24_g471__1881(.A0N (inc_add_136_24_n_410), .A1N
       (count_s[3]), .B0 (inc_add_136_24_n_405), .Y (n_182));
  AND2X1 inc_add_136_24_g472__5115(.A (inc_add_136_24_n_410), .B
       (count_s[3]), .Y (inc_add_136_24_n_405));
  AOI21XL inc_add_136_24_g473__7482(.A0 (inc_add_136_24_n_415), .A1
       (inc_add_136_24_n_419), .B0 (inc_add_136_24_n_410), .Y (n_183));
  NOR2XL inc_add_136_24_g474__4733(.A (inc_add_136_24_n_415), .B
       (inc_add_136_24_n_419), .Y (inc_add_136_24_n_410));
  OA21X1 inc_add_136_24_g475__6161(.A0 (count_s[0]), .A1 (count_s[1]),
       .B0 (inc_add_136_24_n_415), .Y (n_184));
  NAND2XL inc_add_136_24_g476__9315(.A (count_s[0]), .B (count_s[1]),
       .Y (inc_add_136_24_n_415));
  CLKINVX1 inc_add_136_24_g477(.A (count_s[6]), .Y
       (inc_add_136_24_n_418));
  CLKINVX1 inc_add_136_24_g478(.A (count_s[2]), .Y
       (inc_add_136_24_n_419));
  CLKINVX1 inc_add_136_24_g479(.A (count_s[10]), .Y
       (inc_add_136_24_n_422));
  CLKINVX1 inc_add_136_24_g480(.A (count_s[14]), .Y
       (inc_add_136_24_n_425));
  CLKINVX1 inc_add_136_24_g481(.A (count_s[24]), .Y
       (inc_add_136_24_n_426));
  INVX1 inc_add_136_24_g482(.A (count_s[0]), .Y (n_185));
  CLKINVX1 inc_add_136_24_g483(.A (count_s[18]), .Y
       (inc_add_136_24_n_445));
endmodule

module top_dut(mclk, reset, start, slave_rd_wr, master_rd_wr,
     slave_address, master_address, master_in_data, master_out_data,
     slave_in_data, slave_out_data);
  input mclk, reset, start, master_rd_wr;
  input [6:0] master_address;
  input [7:0] master_out_data, slave_out_data;
  output slave_rd_wr;
  output [6:0] slave_address;
  output [7:0] master_in_data, slave_in_data;
  wire mclk, reset, start, master_rd_wr;
  wire [6:0] master_address;
  wire [7:0] master_out_data, slave_out_data;
  wire slave_rd_wr;
  wire [6:0] slave_address;
  wire [7:0] master_in_data, slave_in_data;
  wire UNCONNECTED56, cs, miso, mosi;
  spi_master m(mclk, reset, start, master_rd_wr, master_address,
       master_in_data, master_out_data, miso, mosi, cs, UNCONNECTED56);
  spi_slave s(mclk, reset, cs, mosi, miso, slave_rd_wr, slave_address,
       slave_in_data, slave_out_data);
endmodule

