
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Nov 20 2024 20:30:23 IST (Nov 20 2024 15:00:23 UTC)

// Verification Directory fv/SPI_Protocol 

module SPI_Protocol(start, clk, data_in_master, data_in_slave,
     data_out_master, load, data_out_slave, CPOL, CPHA, Address,
     reset1, reset2, reset3);
  input start, clk, load, CPOL, CPHA, reset1, reset2, reset3;
  input [7:0] data_in_master, data_in_slave;
  input [1:0] Address;
  output [7:0] data_out_master, data_out_slave;
  wire start, clk, load, CPOL, CPHA, reset1, reset2, reset3;
  wire [7:0] data_in_master, data_in_slave;
  wire [1:0] Address;
  wire [7:0] data_out_master, data_out_slave;
  wire [7:0] data_out_slave1;
  wire [7:0] data_out_slave2;
  wire [7:0] data_out_slave3;
  wire CS1, CS2, CS3, MISO, MISO1, MISO2, MISO3, MOSI;
  wire SCLK, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, slave_start;
  SPI_Master master(clk, start, load, data_in_master, Address, CPOL,
       CPHA, MISO, SCLK, CS1, CS2, CS3, MOSI, data_out_master,
       slave_start);
  SPI_Slave slave_1(reset1, data_in_slave, CPOL, CPHA, SCLK, CS1,
       MISO1, MOSI, slave_start, data_out_slave1);
  SPI_Slave slave_2(reset2, data_in_slave, CPOL, CPHA, SCLK, CS2,
       MISO2, MOSI, slave_start, data_out_slave2);
  SPI_Slave slave_3(reset3, data_in_slave, CPOL, CPHA, SCLK, CS3,
       MISO3, MOSI, slave_start, data_out_slave3);
  INVXL g510(.A (n_9), .Y (data_out_slave[3]));
  INVXL g511(.A (n_8), .Y (data_out_slave[5]));
  INVXL g512(.A (n_7), .Y (data_out_slave[7]));
  INVXL g513(.A (n_6), .Y (data_out_slave[2]));
  AOI222XL g514__2398(.A0 (data_out_slave2[3]), .A1 (n_1), .B0
       (data_out_slave3[3]), .B1 (Address[1]), .C0 (n_0), .C1
       (data_out_slave1[3]), .Y (n_9));
  AOI222XL g515__5107(.A0 (data_out_slave1[5]), .A1 (n_0), .B0
       (data_out_slave3[5]), .B1 (Address[1]), .C0 (n_1), .C1
       (data_out_slave2[5]), .Y (n_8));
  AOI222XL g516__6260(.A0 (data_out_slave1[7]), .A1 (n_0), .B0
       (data_out_slave3[7]), .B1 (Address[1]), .C0 (n_1), .C1
       (data_out_slave2[7]), .Y (n_7));
  AOI222XL g517__4319(.A0 (data_out_slave1[2]), .A1 (n_0), .B0
       (data_out_slave3[2]), .B1 (Address[1]), .C0 (n_1), .C1
       (data_out_slave2[2]), .Y (n_6));
  INVXL g518(.A (n_5), .Y (data_out_slave[4]));
  INVXL g519(.A (n_4), .Y (data_out_slave[1]));
  INVXL g520(.A (n_3), .Y (data_out_slave[6]));
  INVXL g521(.A (n_2), .Y (data_out_slave[0]));
  AOI222XL g522__8428(.A0 (data_out_slave1[4]), .A1 (n_0), .B0
       (data_out_slave3[4]), .B1 (Address[1]), .C0 (n_1), .C1
       (data_out_slave2[4]), .Y (n_5));
  AOI222XL g523__5526(.A0 (data_out_slave2[1]), .A1 (n_1), .B0
       (data_out_slave3[1]), .B1 (Address[1]), .C0 (n_0), .C1
       (data_out_slave1[1]), .Y (n_4));
  AOI222XL g524__6783(.A0 (data_out_slave2[6]), .A1 (n_1), .B0
       (data_out_slave3[6]), .B1 (Address[1]), .C0 (n_0), .C1
       (data_out_slave1[6]), .Y (n_3));
  AOI222XL g525__3680(.A0 (data_out_slave2[0]), .A1 (n_1), .B0
       (data_out_slave3[0]), .B1 (Address[1]), .C0 (n_0), .C1
       (data_out_slave1[0]), .Y (n_2));
  MX3XL g526__1617(.A (MISO1), .B (MISO2), .C (MISO3), .S0
       (Address[0]), .S1 (Address[1]), .Y (MISO));
  NOR2BXL g527__2802(.AN (Address[0]), .B (Address[1]), .Y (n_1));
  NOR2XL g528__1705(.A (Address[0]), .B (Address[1]), .Y (n_0));
endmodule

