
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Nov 20 2024 20:23:41 IST (Nov 20 2024 14:53:41 UTC)

// Verification Directory fv/SPI_Pro_tb 

module SPI_Pro_tb;
endmodule

